### PR TITLE
Move CI to GHA

### PR DESCRIPTION
**Pull request by gigimon**
https://github.com/gigimon/proxy-model.py/runs/4381248197?check_suite_focus=true

┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-204) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by vasiliy-zaznobin — COMMENTED** [review]
Buildkite allows you to save artifacts, this is not here.
@s-medvedev, @otselnik  review please too

**Comment by gigimon** [comment]
@vasiliy-zaznobin fixed :) https://github.com/gigimon/proxy-model.py/actions/runs/1530429217

**Comment by vasiliy-zaznobin** [comment]
@gigimon  Which version of the neon-evm was used?
Can we run a build of neon-proxy with a different version of neon-evm?

**Comment by Agronomistech** [comment]
> @gigimon Which version of the neon-evm was used?
> Can we run a build of neon-proxy with a different version of neon-evm?

We run neonlabsorg/evm_loader:latest container by default and build container only for proxy-model.py. I think I can add this as variable. If you have more options, please say, I will add it

**Pull request closed without merging**
